server:
  port: 8085
spring:
  redis:
    host: 192.168.226.130
dubbo:
  application:
    name: shop_cart
  registry:
    address: zookeeper://192.168.226.130:2181
  consumer:
    check: false
    timeout: 1000